# Generated by Django 4.1.7 on 2024-04-06 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('login', models.DateTimeField(max_length=200, verbose_name='Начало')),
                ('logout', models.DateTimeField(max_length=200, verbose_name='Конец')),
                ('status', models.CharField(choices=[('notviewed', 'Новая'), ('yes', 'Одобрена'), ('no', 'Не одобрена')], default='notviewed', max_length=15, verbose_name='Статус заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('img', models.ImageField(upload_to='sports/%Y/%m/%d/', verbose_name='Картинка')),
                ('body', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('surname', models.CharField(max_length=55, verbose_name='Фамилия')),
                ('img', models.ImageField(upload_to='trainers/%Y/%m/%d/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=25)),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.sport', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('physical', models.CharField(max_length=50, verbose_name='Уровень физической подготовки')),
                ('img', models.ImageField(upload_to='users/%Y/%m/%d', verbose_name='Фото')),
                ('preferences', models.ManyToManyField(blank=True, to='custom_authapp.sport', verbose_name='Предпочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.attendance', verbose_name='Тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.sport', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.trainer', verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Почта'),
        ),
    ]
