# Generated by Django 4.2.11 on 2024-04-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('img', models.ImageField(upload_to='sports/%Y/%m/%d/', verbose_name='Картинка')),
                ('body', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
