# Generated by Django 4.1.7 on 2024-04-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('notviewed', 'Не просмотрена'), ('yes', 'Одобрена'), ('no', 'Не одобрена')], default='notviewed', max_length=15, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
