# Generated by Django 4.1.7 on 2024-04-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
