# Generated by Django 4.1.7 on 2024-04-09 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_authapp', '0002_remove_comment_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentAttendence',
        ),
        migrations.AlterModelOptions(
            name='commentattendence',
            options={'verbose_name': 'Комментарий для тренировки', 'verbose_name_plural': 'Комментарии для тренировок'},
        ),
        migrations.CreateModel(
            name='CommentTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.trainer', verbose_name='Тренировка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий для тренера',
                'verbose_name_plural': 'Комментарии для тренеров',
            },
        ),
    ]
