# Generated by Django 4.1.7 on 2024-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0002_alter_attendance_status_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=25, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата устройства'),
        ),
    ]
