# Generated by Django 4.2.11 on 2024-04-04 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0003_remove_trainer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='salary',
        ),
        migrations.AddField(
            model_name='trainer',
            name='experience',
            field=models.CharField(default=1, max_length=50, verbose_name='Опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='img',
            field=models.ImageField(default=1, upload_to='trainers/%Y/%m/%d/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.sport', verbose_name='Специализация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='surname',
            field=models.CharField(default=1, max_length=55, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Имя'),
        ),
    ]
