# Generated by Django 4.1.7 on 2024-04-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0003_rename_comment_commentattendence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttrainer',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_authapp.trainer', verbose_name='Тренер'),
        ),
    ]
