# Generated by Django 4.2.11 on 2024-04-04 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_authapp', '0005_alter_sport_options_alter_trainer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='phone',
        ),
        migrations.AddField(
            model_name='attendance',
            name='email',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
