# Generated by Django 4.2.11 on 2024-04-04 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_authapp', '0006_remove_attendance_phone_attendance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Телефон'),
        ),
    ]
