# Generated by Django 4.2.11 on 2024-04-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0007_alter_attendance_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='email',
            new_name='user',
        ),
    ]
