# Generated by Django 4.2.11 on 2024-04-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_authapp', '0009_delete_membershipplan_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='login',
            field=models.DateTimeField(max_length=200, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logout',
            field=models.DateTimeField(max_length=200, verbose_name='Конец'),
        ),
    ]
